
{{< include _math.qmd >}}

```{r setup, include=FALSE}
source('_setup.R')
```

# Apresentação {.unnumbered}

Este livro eletrônico --- um trabalho em construção --- reúne soluções dos exercícios do livro *Elementos de Matemática Discreta para Computação*, de autoria de Anamaria Gomide e Jorge Stolfi [@anamaria23:_elemen_matem_discr_comput], disponível em <https://www.ic.unicamp.br/~stolfi/fmc-book/2022-08-24-js/livro.pdf>.

Além das soluções teóricas, incluímos código em SETLX (*Set Language Extended*), uma linguagem de programação de alto nível projetada especificamente para resolver problemas envolvendo conjuntos, relações, funções e outros objetos estudados em um curso de Matemática Discreta.

Para saber mais sobre SETLX --- incluindo como instalar a liguagem nos principais sistemas operacionais --- visite <https://randoom.org/Software/SetlX/>. Um tutorial completo de SETLX está disponível em <https://download.randoom.org/setlX/tutorial.pdf>.


## Agradecimentos {.unnumbered}

Muitas das soluções foram desenvolvidas ao longo do ano de 2024 pelos alunos da disciplina de Matemática Discreta do curso de Ciência da Computação do Pólo de Rio das Ostras da Universidade Federal Fluminense.


