---
format:
  
  html:
    toc-depth: 3
    number-depth: 3
    theme: 
      - journal
      - _custom.scss

  pdf:
    documentclass: scrreprt
    toc-depth: 3
    number-depth: 3
    fig-pos: htb
    keep-tex: true
    df-print: tibble
    filters: 
      - filters/dollar.lua
      - filters/hl.lua
    include-in-header: 
      - _preamble.tex
    include-before-body:  
      - _before-body.tex

---

```{r setup, include=FALSE}
source('_setup.R')
```


# Tabela com math

Original:

```{r echo=FALSE}
tibble(
  x = c(
    '\\(-\\sqrt{3}\\)', 
    '\\(-\\sqrt{2}\\)', 
    '\\(\\sqrt{2}\\)', 
    '\\(\\sqrt{3}\\)'
  ) %>% 
    map_chr(md),
  y = c(4, 3, 3, 4) %>% 
    paste0('\\(', ., '\\)') %>% 
    map_chr(md)
) %>% 
  gt() %>% 
    cols_label(
      x = '\\(x\\)' %>% map_chr(md),
      y = '\\(x^2 + 1\\)' %>% map_chr(md)
    ) %>% 
  cols_align('right')
```

Com vec_fmt_markdown:

```{r echo=FALSE}
tibble(
  x = c(
    '$-\\sqrt{3}$', 
    '$-\\sqrt{2}$', 
    '$\\sqrt{2}$', 
    '$\\sqrt{3}$'
  ) %>% 
    vec_fmt_markdown(),
  y = c(4, 3, 3, 4) %>% 
    paste0('$', ., '$') %>% 
    vec_fmt_markdown()
) %>% 
  gt() %>% 
    cols_label(
      x = '$x$' %>% md(),
      y = '$x^2 + 1$' %>% md()
    ) %>% 
  cols_align('right') %>% 
  fmt_passthrough(rows = everything(), escape = FALSE)
```

# Callouts

::: {.callout-note title="Note"}

bla

:::

::: {.callout-warning title="Warning"}

bla

:::

::: {.callout-important title="Important"}

bla

:::

::: {.callout-tip title="Tip"}

bla

:::

::: {.callout-caution title="Caution"}

bla

:::




1. Vamos dizer que o conjunto $A$ é

   $$
   A = \{ a_1, a_2, \ldots, a_n \}
   $$
   
   Não sabemos o valor de $n$ (pode até ser zero, no caso do conjunto vazio), nem quem são os elementos (podem até ser outros conjuntos). Esta é a idéia de $A$ ser arbitrário.

